docker-compose-yaml: docker-compose.yml

project: "lagoon-sync"

ssh:
  host: "example.ssh.lagoon.amazeeio.cloud"
  port: 3222
  privateKey: "~/.ssh/example_id_rsa"
  verbose: true

lagoon-sync:
  mariadb:
    config:
      hostname: "$MARIADB_HOST"
      username: "$MARIADB_USERNAME"
      password: "$MARIADB_PASSWORD"
      port: "$MARIADB_PORT"
      database: "$MARIADB_DATABASE"
      ignore-table:
        - "cachewhatever"
        - "someothertable"
      ignore-table-data:
        - "cache_data"
        - "cache_menu"
    local:
      config:
        hostname: "drupal"
        username: "drupal"
        password: "drupal"
        port: "3306"
        database: "drupal"
#     postgres:
#       config:
#         hostname: "$POSTGRES_HOST"
#         username: "$POSTGRES_USERNAME"
#         password: "$POSTGRES_PASSWORD"
#         port: "5432"
#         database: "$POSTGRES_DATABASE"
#         exclude-table:
#           - cachewhatever
#           - someothertable
#         exclude-table-data:
#           - cache_data
#           - cache_menu
#       local:
#         config:
#           hostname: "drupal"
#           username: "drupal"
#           password: "drupal"
#           port: "3306"
#           database: "drupal"
  mongodb:
    config:
      hostname: "$HOSTNAME"
      port: "$MONGODB_SERVICE_PORT"
      database: "local"
    local:
      config:
        hostname: "$HOSTNAME"
        port: "27017"
        database: "local"
#     files:
#       config:
#         sync-directory: "/app/storage"
#         exclude:
#           - "app"
#           - "framework"
#       local:
#         config:
#           sync-directory: "/tmp/storageout"
#     drupalconfig:
#       config:
#         syncpath: "./config/sync"
#       local:
#         overrides:
#           config:
#             syncpath: "./config/sync"
